[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  NEXT_PUBLIC_SUPABASE_URL = "https://smbxcbpnscdrzlfmimyo.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtYnhjYnBuc2NkcnpsZm1pbXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzMzU1MzgsImV4cCI6MjA4NDkxMTUzOH0.XWkMMwNS9Mw2wX1tIqNWbl91ngPz6B1SasEHkS8yULI"

[[plugins]]
  package = "@netlify/plugin-nextjs"